on:
    push:
        branches:
            - main

name: ⏫ Sync content to FMS

jobs:
    copy-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # Copy the 'post' folder
            - name: Push lastest css file
              uses: Indira-kumar/sync_file_to_another_repo_action@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source_file: "common/style.css" # Source File to sync
                  destination_repo: "Indira-kumar/fms-sync-file" # Target repo
                  destination_folder: "common/" # Destination folder where to sync 
                  user_email: "indirakumarak@gmail.com"
                  user_name: "Indira-kumar"
                  commit_message: "AUTO: Sync common files from Maker" 
                #   Change it to ${{ github.event.head_commit.message }} to preserve the original commit message
                  git_server: "github.com"
